### ISSUE TITLE
Double tweets

### ISSUE THREAD

**Issue by puddingtown** [BabDev/Tweet-Display-Back#84]
Hi, 
we just updated on www.erlebnismanger.info the twitter module to version 3.0.3 due of the twitter changes. 
Since that update all tweets are shown two times. Setting at this time is 1 tweet and you see it twice. 
Any idea how to fix?
Kind regards
Chris

**Comment by chlorinekid** [comment]
just noticed the double tweet issue on one of our sites. will try the modified helper file and see if this fixes it..
