### ISSUE TITLE
Error 0 : Could not retrieve bearer token (consumer)

### ISSUE THREAD

**Issue by mikeveeckmans** [BabDev/Tweet-Display-Back#99]
Hi,
I installed the tweet display back module on the homepage of a project. Once in a while ( i know that it's probably a twitter issue ) the communication between the module and twitter is lost (i think) and this gives an error, however instead of just the module showing an error , the complete site goes down as shown in http://www.screencast.com/t/uIenGe9TEpiW .
Is there a failover ? 

Version : 3.1.0
Joomla! 3.4.8

**Comment by mbabker** [comment]
Current code has a catch added for errors instantiating the helpers which will display a friendly message instead of bubbling up to the global error handler, best that can be done if an error gets thrown here.
